### ISSUE TITLE
How can i get the message for topic "camera_info"?

### ISSUE THREAD

**Issue by ccs-ros** [RobustFieldAutonomyLab/bluerov#1]
Hi,recently，i am using the bluerov2.This document  is very helpful to me.I want to run the orbslam2 using the camera of the bluerov2. And,when i used the camera,i can not found the message for ROS topic "camera_info",so that the camera calibration work can not be done.Can you give me some advice to help me solve this problem? Thank you very much!

**Comment by jinkunw** [comment]
I added the function to publish camera_info, and you need to put the calibration config to `~/.ros/camera_info/camera.yaml`. Let me know if this works.

**Comment by ccs-ros** [comment]
@jinkunw it works well,Thank you!
