### ISSUE TITLE
How to get the specific angle and distance information of an obstacle from ros topic?

### ISSUE THREAD

**Issue by ccs-ros** [RobustFieldAutonomyLab/bluerov#2]
I have another question,what‘s the data in the message "ping"? Is the echo intensity value? If i want to get the specific angle and distance information of an obstacle，what shoud i do?

**Comment by jinkunw** [comment]
Check the definition of [ping msg](https://github.com/RobustFieldAutonomyLab/bluerov/blob/master/sonar_oculus/msg/OculusPing.msg).

Basically, the [image filed](https://github.com/RobustFieldAutonomyLab/bluerov/blob/6d08b76d98fb924c9468cc3b1318e195ba9bfe8f/sonar_oculus/msg/OculusPing.msg#L5) encodes the intensity of echo return at a specific range (row) and bearing (column). So pixel at the ith row and jth column in the image refers to intensity at `bearings[j]` and `range_resolution x (i + 1)`.
